# Generated by Django 4.1 on 2022-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='photo',
        ),
    ]
